version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "50051:50051"
    volumes:
      - .:/app
      - camera_pics:/app/CAMERAPIC
      - model_cache:/root/.u2net
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TRENDSTORY_HOST=0.0.0.0
      - TRENDSTORY_PORT=50051
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped

volumes:
  camera_pics:
  model_cache: 