# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import trendstory_pb2 as trendstory__pb2


class TrendStoryStub(object):
    """Service definition for TrendStory microservice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/trendstory.TrendStory/Generate',
                request_serializer=trendstory__pb2.GenerateRequest.SerializeToString,
                response_deserializer=trendstory__pb2.GenerateResponse.FromString,
                )


class TrendStoryServicer(object):
    """Service definition for TrendStory microservice
    """

    def Generate(self, request, context):
        """Generates a themed story based on trending topics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrendStoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=trendstory__pb2.GenerateRequest.FromString,
                    response_serializer=trendstory__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trendstory.TrendStory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrendStory(object):
    """Service definition for TrendStory microservice
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trendstory.TrendStory/Generate',
            trendstory__pb2.GenerateRequest.SerializeToString,
            trendstory__pb2.GenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
