# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/trendstory.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/trendstory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/trendstory.proto\x12\ntrendstory\"S\n\x0fGenerateRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x12\n\nimage_path\x18\x04 \x01(\t\"\xa6\x01\n\x10GenerateResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x13\n\x0btopics_used\x18\x04 \x03(\t\x12+\n\x08metadata\x18\x05 \x01(\x0b\x32\x19.trendstory.StoryMetadata\x12\x15\n\rdetected_mood\x18\x06 \x01(\t\"i\n\rStoryMetadata\x12\x17\n\x0fgeneration_time\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\r\n\x05theme\x18\x04 \x01(\t\x12\x0c\n\x04mood\x18\x05 \x01(\t2U\n\nTrendStory\x12G\n\x08Generate\x12\x1b.trendstory.GenerateRequest\x1a\x1c.trendstory.GenerateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.trendstory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=38
  _globals['_GENERATEREQUEST']._serialized_end=121
  _globals['_GENERATERESPONSE']._serialized_start=124
  _globals['_GENERATERESPONSE']._serialized_end=290
  _globals['_STORYMETADATA']._serialized_start=292
  _globals['_STORYMETADATA']._serialized_end=397
  _globals['_TRENDSTORY']._serialized_start=399
  _globals['_TRENDSTORY']._serialized_end=484
# @@protoc_insertion_point(module_scope)
